### ISSUE TITLE
Mobile Enhancements

### ISSUE THREAD

**Issue by cocoacacao** [Alder-S/alder-s.github.io#4]
On mobile, the website generally looks good. However, the home screen is oddly scrunched into the top half of the screen, and the background image only tiles twice, resulting in a white border when zooming out too far, easily fixed by adding the background color back in underneath the image.

**Comment by vocatart** [comment]
Re-arranging the website for a mobile layout is too big of a project at the moment, and should be handled at a later date. The tiling issue has been fixed, and the background color has been set to verdegris behind the background photo.
